robot_control:
  robot_ip: "192.168.20.35"
  robot_port: 30003
  reconnect_interval: 5.0
  socket_timeout: 5.0
  acceleration: 1.0
  max_speed: 0.5
  workspace_limits:
    x_min: -0.4
    x_max: 0.4
    y_min: -0.4
    y_max: 0.4
    z_min: 0.1
    z_max: 0.4
servoj:
  time: 0.008
  lookahead_time: 0.15
  gain: 200