move_group:
  ros__parameters:
    scaled_joint_trajectory_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - left_shoulder_pan_joint
        - left_shoulder_lift_joint
        - left_elbow_joint
        - left_wrist_1_joint
        - left_wrist_2_joint
        - left_wrist_3_joint
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_elbow_joint
        - right_wrist_1_joint
        - right_wrist_2_joint
        - right_wrist_3_joint
      default: true
    gripper_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - left_joint_finger_1
        - left_joint_finger_2
        - right_joint_finger_1
        - right_joint_finger_2
      default: false