# Default initial positions for dual_ur_robotiq's ros2_control fake system

initial_positions:
  left_elbow_joint: 0
  left_joint_finger_1: 0
  left_joint_finger_2: 0
  left_shoulder_lift_joint: 0
  left_shoulder_pan_joint: 0
  left_wrist_1_joint: 0
  left_wrist_2_joint: 0
  left_wrist_3_joint: 0
  right_elbow_joint: 0
  right_joint_finger_1: 0
  right_joint_finger_2: 0
  right_shoulder_lift_joint: 0
  right_shoulder_pan_joint: 0
  right_wrist_1_joint: 0
  right_wrist_2_joint: 0
  right_wrist_3_joint: 0